import type { CSSProperties } from "react";

// Inline-style tokens for the phone-sized admin dashboard, transcribed from
// the mobile design (screens: dashboard → inline quick actions → details
// sheet → full visit log). Colors ride the same CSS vars as the desktop so
// dark mode stays coherent; the light values match the mock exactly.
export const M: Record<string, CSSProperties> = {
  wrap: {
    minHeight: "100dvh",
    display: "flex",
    flexDirection: "column",
    background: "var(--bg)",
    color: "var(--fg)",
  },
  // Composer block at the top; extra top padding clears notches in PWA mode.
  head: {
    padding: "calc(env(safe-area-inset-top, 0px) + 18px) 20px 14px",
  },
  headRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    margin: "0 0 14px",
  },
  h1: { fontSize: "1.4rem", fontWeight: 600, margin: 0 },
  logout: {
    padding: ".3rem 0",
    fontSize: ".85rem",
    color: "var(--muted)",
    background: "transparent",
    border: "none",
  },
  error: {
    margin: "0 0 12px",
    padding: ".6rem .75rem",
    fontSize: ".85rem",
    color: "var(--danger)",
    border: "1px solid var(--danger)",
    borderRadius: 8,
  },
  composer: { display: "grid", gap: 10 },
  input: {
    width: "100%",
    minHeight: 52,
    padding: ".7rem .75rem",
    fontSize: "1rem",
    color: "var(--fg)",
    background: "var(--field-bg)",
    border: "1px solid var(--border)",
    borderRadius: 8,
  },
  slugRow: { display: "flex", alignItems: "stretch" },
  slugPrefix: {
    display: "flex",
    alignItems: "center",
    padding: "0 .6rem",
    fontSize: ".9rem",
    color: "var(--muted)",
    background: "var(--field-bg)",
    border: "1px solid var(--border)",
    borderRight: "none",
    borderRadius: "8px 0 0 8px",
    whiteSpace: "nowrap",
  },
  slugInput: {
    flex: 1,
    minWidth: 0,
    minHeight: 52,
    padding: ".5rem .75rem",
    fontSize: "1rem",
    color: "var(--fg)",
    background: "var(--field-bg)",
    border: "1px solid var(--border)",
    borderRadius: "0 8px 8px 0",
  },
  save: {
    minHeight: 52,
    fontSize: "1rem",
    fontWeight: 600,
    color: "var(--accent-fg)",
    background: "var(--accent)",
    border: "none",
    borderRadius: 8,
  },

  // "Links · 4" bar with the sort pill on the right.
  listBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "2px 20px 8px",
  },
  label: {
    fontSize: ".7rem",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: ".07em",
    color: "var(--muted)",
  },
  // The pill shows "Newest ▾"; an invisible native <select> stretched over it
  // opens the platform picker on tap.
  sortPill: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    gap: 4,
    minHeight: 30,
    padding: "0 .7rem",
    border: "1px solid var(--border)",
    borderRadius: 999,
    fontSize: ".78rem",
    color: "var(--fg)",
  },
  sortSelect: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    opacity: 0,
    cursor: "pointer",
  },

  list: { flex: 1, borderTop: "1px solid var(--border)" },
  empty: { padding: "20px", color: "var(--muted)", margin: 0 },
  row: { borderBottom: "1px solid var(--border)" },
  // The row whose details sheet is open, highlighted beneath the scrim.
  rowActive: {
    borderBottom: "1px solid var(--border)",
    background: "var(--surface)",
  },
  rowBtn: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    minHeight: 66,
    width: "100%",
    padding: "12px 20px",
    background: "none",
    border: "none",
    font: "inherit",
    color: "inherit",
    textAlign: "left",
  },
  rowMain: { flex: 1, minWidth: 0 },
  rowSlug: { fontWeight: 600 },
  rowNote: {
    fontSize: ".82rem",
    color: "var(--fg)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  rowDest: {
    fontSize: ".8rem",
    color: "var(--muted)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  rowStats: { textAlign: "right", whiteSpace: "nowrap" },
  rowStat: { fontSize: ".7rem", color: "var(--muted)" },
  offBadge: {
    fontSize: ".62rem",
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: ".03em",
    color: "var(--danger)",
    border: "1px solid var(--danger)",
    borderRadius: 4,
    padding: "0 .3rem",
    marginLeft: 6,
    verticalAlign: "middle",
  },
  toast: {
    position: "fixed",
    left: "50%",
    bottom: "calc(env(safe-area-inset-bottom, 0px) + 44px)",
    transform: "translateX(-50%)",
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "10px 16px",
    background: "var(--accent)",
    color: "var(--accent-fg)",
    borderRadius: 999,
    fontSize: ".85rem",
    fontWeight: 600,
    boxShadow: "0 4px 16px rgba(0,0,0,.25)",
    whiteSpace: "nowrap",
    zIndex: 80,
  },

  // Details bottom sheet over a dimmed dashboard.
  scrim: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,.35)",
    border: "none",
    padding: 0,
    zIndex: 40,
  },
  sheet: {
    position: "fixed",
    left: 0,
    right: 0,
    bottom: 0,
    maxHeight: "min(600px, 88dvh)",
    overflowY: "auto",
    background: "var(--bg)",
    borderRadius: "18px 18px 0 0",
    boxShadow: "0 -8px 30px rgba(0,0,0,.18)",
    padding: "10px 20px calc(env(safe-area-inset-bottom, 0px) + 24px)",
    zIndex: 50,
  },
  handle: {
    width: 38,
    height: 5,
    borderRadius: 999,
    background: "var(--border)",
    margin: "0 auto 12px",
  },
  sheetHead: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
  },
  sheetTitle: { flex: 1, minWidth: 0 },
  sheetSlug: { fontSize: "1.15rem", fontWeight: 600 },
  sheetDest: {
    fontSize: ".82rem",
    color: "var(--muted)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  close: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
    height: 32,
    borderRadius: "50%",
    background: "var(--surface)",
    color: "var(--muted)",
    fontSize: ".9rem",
    border: "none",
    flexShrink: 0,
  },
  turnOn: {
    width: "100%",
    minHeight: 46,
    fontSize: ".9rem",
    fontWeight: 600,
    color: "var(--accent-fg)",
    background: "var(--accent)",
    border: "none",
    borderRadius: 8,
    marginBottom: 8,
  },
  actionGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 8,
    marginBottom: 14,
  },
  actionPrimary: {
    minHeight: 46,
    fontSize: ".9rem",
    fontWeight: 600,
    color: "var(--accent-fg)",
    background: "var(--accent)",
    border: "none",
    borderRadius: 8,
  },
  actionBtn: {
    minHeight: 46,
    fontSize: ".9rem",
    fontWeight: 600,
    color: "var(--fg)",
    background: "var(--field-bg)",
    border: "1px solid var(--border)",
    borderRadius: 8,
  },
  // The note is a bare always-editable box: styled like the read-only note
  // card it replaced, auto-grown to its content (no visible resize).
  noteArea: {
    display: "block",
    width: "100%",
    padding: ".6rem .7rem",
    fontSize: ".85rem",
    fontFamily: "inherit",
    lineHeight: 1.5,
    color: "var(--fg)",
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 8,
    margin: "0 0 12px",
    resize: "none",
    overflow: "hidden",
  },
  // Inline editors inside the sheet (destination URL, note).
  editArea: { display: "grid", gap: 8, margin: "0 0 12px" },
  editInput: {
    width: "100%",
    minHeight: 44,
    padding: ".5rem .7rem",
    fontSize: ".9rem",
    color: "var(--fg)",
    background: "var(--field-bg)",
    border: "1px solid var(--border)",
    borderRadius: 8,
  },
  editActions: { display: "flex", gap: 8, justifyContent: "flex-end" },
  editBtn: {
    minHeight: 36,
    padding: "0 .9rem",
    fontSize: ".85rem",
    fontWeight: 600,
    color: "var(--fg)",
    background: "var(--field-bg)",
    border: "1px solid var(--border)",
    borderRadius: 8,
  },
  editSave: {
    minHeight: 36,
    padding: "0 .9rem",
    fontSize: ".85rem",
    fontWeight: 600,
    color: "var(--accent-fg)",
    background: "var(--accent)",
    border: "none",
    borderRadius: 8,
  },
  statsRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "1.1rem",
    padding: "0 0 10px",
    fontSize: ".8rem",
    color: "var(--muted)",
    borderBottom: "1px solid var(--border)",
  },
  statStrong: { fontWeight: 600, color: "var(--fg)" },
  visitsHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 40,
  },
  seeAll: {
    fontSize: ".8rem",
    fontWeight: 600,
    padding: ".3rem 0",
    color: "var(--fg)",
    background: "none",
    border: "none",
  },
  visitRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: ".6rem",
    padding: ".35rem 0",
    fontSize: ".8rem",
  },
  visitRowLine: { borderTop: "1px solid var(--border)" },
  visitLeft: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  visitWhen: { fontWeight: 600 },
  visitSrc: { flex: "none", color: "var(--muted)" },
  visitSrcDenied: { flex: "none", color: "var(--danger)" },
  visitsNote: { padding: ".4rem 0 0", fontSize: ".75rem", color: "var(--muted)" },
  muted: { color: "var(--muted)", fontSize: ".8rem", padding: ".35rem 0" },
  delete: {
    width: "100%",
    minHeight: 46,
    fontSize: ".9rem",
    fontWeight: 600,
    color: "var(--danger)",
    background: "var(--danger-soft)",
    border: "1px solid var(--danger-soft-border)",
    borderRadius: 8,
    marginTop: 20,
  },
  deleteHint: {
    marginTop: 6,
    textAlign: "center",
    fontSize: ".72rem",
    color: "var(--muted)",
  },

  // Full-screen visit log ("See all").
  screen: {
    position: "fixed",
    inset: 0,
    background: "var(--bg)",
    color: "var(--fg)",
    zIndex: 70,
    display: "flex",
    flexDirection: "column",
  },
  vHead: {
    padding: "calc(env(safe-area-inset-top, 0px) + 14px) 20px 12px",
    borderBottom: "1px solid var(--border)",
    flexShrink: 0,
  },
  vHeadRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    margin: "0 0 10px",
  },
  back: {
    display: "flex",
    alignItems: "center",
    minHeight: 44,
    padding: "0 .4rem 0 0",
    fontSize: "1rem",
    color: "var(--fg)",
    background: "none",
    border: "none",
    whiteSpace: "nowrap",
  },
  vTitle: { flex: 1, minWidth: 0, textAlign: "center", fontWeight: 600 },
  vSpacer: { width: 52, flexShrink: 0 },
  chips: { display: "flex", gap: 8, overflowX: "auto" },
  chip: {
    display: "flex",
    alignItems: "center",
    minHeight: 36,
    padding: "0 .8rem",
    border: "1px solid var(--border)",
    borderRadius: 999,
    fontSize: ".8rem",
    background: "none",
    color: "var(--fg)",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  chipActive: {
    display: "flex",
    alignItems: "center",
    minHeight: 36,
    padding: "0 .8rem",
    border: "1px solid var(--accent)",
    borderRadius: 999,
    fontSize: ".8rem",
    fontWeight: 600,
    background: "var(--accent)",
    color: "var(--accent-fg)",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  vScroll: { flex: 1, overflowY: "auto" },
  chartCard: { padding: "12px 20px 14px", borderBottom: "1px solid var(--border)" },
  chartHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: ".8rem",
    marginBottom: 8,
  },
  rangeSeg: {
    display: "flex",
    border: "1px solid var(--border)",
    borderRadius: 7,
    overflow: "hidden",
  },
  rangeBtn: {
    minHeight: 32,
    padding: "0 .6rem",
    fontSize: ".72rem",
    fontWeight: 600,
    color: "var(--muted)",
    background: "var(--bg)",
    border: "none",
  },
  rangeBtnActive: {
    minHeight: 32,
    padding: "0 .6rem",
    fontSize: ".72rem",
    fontWeight: 600,
    color: "var(--accent-fg)",
    background: "var(--accent)",
    border: "none",
  },
  chartStats: {
    display: "flex",
    flexWrap: "wrap",
    gap: "1rem",
    marginBottom: 10,
    fontSize: ".78rem",
    color: "var(--muted)",
  },
  bars: { display: "flex", alignItems: "flex-end", gap: 3, height: 64 },
  bar: {
    flex: 1,
    minWidth: 0,
    background: "var(--border)",
    borderRadius: "2px 2px 0 0",
  },
  axis: {
    display: "flex",
    justifyContent: "space-between",
    marginTop: 5,
    fontSize: ".68rem",
    color: "var(--muted)",
  },
  dayLabel: { padding: "10px 20px 4px" },
  logRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    padding: ".55rem 20px",
    borderBottom: "1px solid var(--border)",
  },
  logLeft: { display: "grid", gap: ".1rem", minWidth: 0 },
  logTime: { fontWeight: 600, fontSize: ".9rem" },
  logMeta: {
    fontSize: ".8rem",
    color: "var(--muted)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  logRight: { display: "grid", gap: ".1rem", textAlign: "right", flex: "none" },
  logPlace: { fontSize: ".8rem" },
  logSrc: { fontSize: ".74rem", color: "var(--muted)" },
  logSrcDenied: { fontSize: ".74rem", color: "var(--danger)" },
  vFooter: {
    padding: "14px 20px calc(env(safe-area-inset-bottom, 0px) + 14px)",
    fontSize: ".8rem",
    color: "var(--muted)",
    textAlign: "center",
  },
  vEmpty: { padding: "28px 20px", color: "var(--muted)", textAlign: "center" },
};
