import type { CSSProperties } from "react";

// Inline-style tokens for the admin screen, shared by the page and its
// blocks. One object keeps related styles greppable; graduate to CSS modules
// if this ever needs media queries or pseudo-classes beyond globals.css.
export const S: Record<string, CSSProperties> = {
  page: {
    minHeight: "100dvh",
    display: "grid",
    placeItems: "start center",
    padding: "min(5vh, 2.5rem) 1.25rem",
  },
  // Wide card for the unlocked two-column admin; narrow one for the lock
  // screen, where full-width inputs would look silly.
  card: { width: "100%", maxWidth: 1080 },
  cardNarrow: { width: "100%", maxWidth: 560 },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    margin: "0 0 1.25rem",
  },
  // Sidebar (new-link form + Touch ID) beside the links list on a laptop;
  // flex-wrap stacks them back into one column on narrow screens.
  columns: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "flex-start",
    gap: "2rem 3rem",
  },
  sidebar: {
    flex: "1 1 260px",
    minWidth: 0,
    display: "grid",
    gap: "1.5rem",
  },
  mainCol: { flex: "2 1 340px", minWidth: 0 },
  h1: { fontSize: "1.5rem", fontWeight: 600, margin: 0 },
  form: { display: "grid", gap: "1rem" },
  label: {
    display: "grid",
    gap: ".4rem",
    fontSize: ".85rem",
    color: "var(--muted)",
  },
  input: {
    width: "100%",
    padding: ".65rem .75rem",
    fontSize: "1rem",
    color: "var(--fg)",
    background: "var(--field-bg)",
    border: "1px solid var(--border)",
    borderRadius: 8,
  },
  slugRow: { display: "flex", alignItems: "stretch" },
  // Segmented switch between the form's two modes: a fresh destination URL,
  // or combining the slug with an existing link.
  modeRow: { display: "flex", gap: ".4rem" },
  modeBtn: {
    flex: 1,
    padding: ".4rem .6rem",
    fontSize: ".8rem",
    fontWeight: 600,
    color: "var(--muted)",
    background: "transparent",
    border: "1px solid var(--border)",
    borderRadius: 8,
    cursor: "pointer",
  },
  modeBtnActive: {
    flex: 1,
    padding: ".4rem .6rem",
    fontSize: ".8rem",
    fontWeight: 600,
    color: "var(--fg)",
    background: "var(--field-bg)",
    border: "1px solid var(--fg)",
    borderRadius: 8,
    cursor: "pointer",
  },
  hint: { fontSize: ".75rem", color: "var(--muted)" },
  slugPrefix: {
    display: "flex",
    alignItems: "center",
    padding: "0 .6rem",
    fontSize: ".9rem",
    color: "var(--muted)",
    background: "var(--field-bg)",
    border: "1px solid var(--border)",
    borderRight: "none",
    borderRadius: "8px 0 0 8px",
    whiteSpace: "nowrap",
  },
  primary: {
    padding: ".65rem 1rem",
    fontSize: "1rem",
    fontWeight: 600,
    color: "var(--accent-fg)",
    background: "var(--accent)",
    border: "none",
    borderRadius: 8,
    cursor: "pointer",
  },
  secondary: {
    padding: ".55rem .9rem",
    fontSize: ".9rem",
    fontWeight: 600,
    color: "var(--fg)",
    background: "var(--field-bg)",
    border: "1px solid var(--border)",
    borderRadius: 8,
    cursor: "pointer",
  },
  textBtn: {
    padding: ".3rem .5rem",
    fontSize: ".85rem",
    color: "var(--muted)",
    background: "transparent",
    border: "none",
    cursor: "pointer",
  },
  divider: {
    display: "grid",
    placeItems: "center",
    position: "relative",
    margin: ".25rem 0",
  },
  dividerText: {
    fontSize: ".8rem",
    color: "var(--muted)",
    background: "var(--bg)",
    padding: "0 .6rem",
  },
  section: { margin: 0, minWidth: 0 },
  sectionLabel: {
    fontSize: ".7rem",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: ".07em",
    color: "var(--muted)",
    margin: "0 0 .75rem",
  },
  footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: ".75rem",
    flexWrap: "wrap",
    paddingTop: "1.25rem",
    borderTop: "1px solid var(--border)",
    fontSize: ".85rem",
  },
  // Section label + sort dropdown share one row above the links list.
  listHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: ".75rem",
    margin: "0 0 .75rem",
  },
  sortLabel: {
    display: "flex",
    alignItems: "center",
    gap: ".4rem",
    fontSize: ".75rem",
    color: "var(--muted)",
  },
  sortSelect: {
    padding: ".2rem .4rem",
    fontSize: ".75rem",
    color: "var(--fg)",
    background: "var(--field-bg)",
    border: "1px solid var(--border)",
    borderRadius: 6,
  },
  list: { listStyle: "none", margin: 0, padding: 0, display: "grid", gap: ".45rem" },
  item: {
    display: "flex",
    flexDirection: "column",
    gap: ".5rem",
    padding: ".6rem .75rem",
    border: "1px solid var(--border)",
    borderRadius: 8,
  },
  itemHead: {
    display: "flex",
    alignItems: "center",
    gap: ".5rem",
    flexWrap: "wrap",
  },
  toolbar: {
    display: "flex",
    alignItems: "center",
    gap: ".4rem",
    flexWrap: "wrap",
  },
  qrBlock: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: ".6rem",
    paddingTop: ".25rem",
  },
  qrCanvas: {
    padding: ".6rem",
    background: "#fff",
    borderRadius: 8,
    lineHeight: 0,
  },
  statsBlock: {
    display: "flex",
    flexDirection: "column",
    gap: ".6rem",
    paddingTop: ".25rem",
    fontSize: ".8rem",
    color: "var(--muted)",
  },
  chips: { display: "flex", flexWrap: "wrap", gap: ".35rem" },
  chip: {
    padding: ".15rem .5rem",
    background: "var(--field-bg)",
    border: "1px solid var(--border)",
    borderRadius: 999,
    fontSize: ".75rem",
    color: "var(--fg)",
  },
  hitList: { display: "grid", gap: ".25rem" },
  hitRow: {
    display: "grid",
    gap: ".1rem",
    padding: ".35rem 0",
    borderTop: "1px solid var(--border)",
  },
  hitTime: { color: "var(--fg)", fontWeight: 600 },
  hitMeta: { fontSize: ".75rem", color: "var(--muted)" },
  shortLink: { fontWeight: 600, textDecoration: "none" },
  clicks: {
    marginLeft: "auto",
    fontSize: ".75rem",
    color: "var(--muted)",
    whiteSpace: "nowrap",
  },
  // Marks a combined link in the list — same shape as the disabled tag, but
  // in the accent color since it's a state, not a problem.
  aliasTag: {
    fontSize: ".7rem",
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: ".03em",
    color: "var(--accent)",
    border: "1px solid var(--accent)",
    borderRadius: 4,
    padding: "0 .35rem",
  },
  disabledTag: {
    fontSize: ".7rem",
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: ".03em",
    color: "var(--danger)",
    border: "1px solid var(--danger)",
    borderRadius: 4,
    padding: "0 .35rem",
  },
  actions: { display: "flex", gap: ".4rem", flexShrink: 0 },
  secondaryBtn: {
    padding: ".3rem .55rem",
    fontSize: ".75rem",
    color: "var(--fg)",
    background: "transparent",
    border: "1px solid var(--border)",
    borderRadius: 6,
    cursor: "pointer",
  },
  dest: {
    fontSize: ".8rem",
    color: "var(--muted)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  note: {
    fontSize: ".8rem",
    color: "var(--fg)",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  noteEditor: {
    display: "flex",
    flexDirection: "column",
    gap: ".5rem",
    paddingTop: ".25rem",
  },
  noteActions: { display: "flex", justifyContent: "flex-end" },
  textarea: {
    width: "100%",
    padding: ".65rem .75rem",
    fontSize: ".9rem",
    fontFamily: "inherit",
    color: "var(--fg)",
    background: "var(--field-bg)",
    border: "1px solid var(--border)",
    borderRadius: 8,
    resize: "vertical",
  },
  delete: {
    flexShrink: 0,
    padding: ".3rem .55rem",
    fontSize: ".75rem",
    color: "var(--danger)",
    background: "transparent",
    border: "1px solid var(--border)",
    borderRadius: 6,
    cursor: "pointer",
  },
  muted: { color: "var(--muted)" },
  // Status banners sit under the header, above both columns, so feedback
  // stays visible no matter how long the links list gets.
  info: {
    margin: "0 0 1.25rem",
    padding: ".6rem .75rem",
    fontSize: ".9rem",
    color: "var(--accent)",
    border: "1px solid var(--accent)",
    borderRadius: 8,
  },
  error: {
    margin: "0 0 1.25rem",
    padding: ".6rem .75rem",
    fontSize: ".9rem",
    color: "var(--danger)",
    border: "1px solid var(--danger)",
    borderRadius: 8,
  },
};
