import type { CSSProperties } from "react";

// Inline-style tokens for the desktop admin (the "2c" two-pane dashboard) and
// the lock screen, shared by the page and its blocks. One object keeps related
// styles greppable; graduate to CSS modules if this ever needs media queries
// or pseudo-classes beyond globals.css.
export const S: Record<string, CSSProperties> = {
  // ── Lock screen / boot ────────────────────────────────────────────────────
  page: {
    minHeight: "100dvh",
    display: "grid",
    placeItems: "start center",
    padding: "min(5vh, 2.5rem) 1.25rem",
  },
  cardNarrow: { width: "100%", maxWidth: 560 },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    margin: "0 0 1.25rem",
  },
  h1: { fontSize: "1.5rem", fontWeight: 600, margin: 0 },
  form: { display: "grid", gap: "1rem" },
  label: {
    display: "grid",
    gap: ".4rem",
    fontSize: ".85rem",
    color: "var(--muted)",
  },
  input: {
    width: "100%",
    padding: ".65rem .75rem",
    fontSize: "1rem",
    color: "var(--fg)",
    background: "var(--field-bg)",
    border: "1px solid var(--border)",
    borderRadius: 8,
  },
  primary: {
    padding: ".65rem 1rem",
    fontSize: "1rem",
    fontWeight: 600,
    color: "var(--accent-fg)",
    background: "var(--accent)",
    border: "none",
    borderRadius: 8,
    cursor: "pointer",
  },
  secondary: {
    padding: ".55rem .9rem",
    fontSize: ".9rem",
    fontWeight: 600,
    color: "var(--fg)",
    background: "var(--field-bg)",
    border: "1px solid var(--border)",
    borderRadius: 8,
    cursor: "pointer",
  },
  divider: {
    display: "grid",
    placeItems: "center",
    position: "relative",
    margin: ".25rem 0",
  },
  dividerText: {
    fontSize: ".8rem",
    color: "var(--muted)",
    background: "var(--bg)",
    padding: "0 .6rem",
  },
  textBtn: {
    padding: ".3rem .5rem",
    fontSize: ".8rem",
    color: "var(--muted)",
    background: "transparent",
    border: "none",
    cursor: "pointer",
  },
  info: {
    margin: "0 0 1.25rem",
    padding: ".6rem .75rem",
    fontSize: ".9rem",
    color: "var(--accent)",
    border: "1px solid var(--accent)",
    borderRadius: 8,
  },
  error: {
    margin: "0 0 1.25rem",
    padding: ".6rem .75rem",
    fontSize: ".9rem",
    color: "var(--danger)",
    border: "1px solid var(--danger)",
    borderRadius: 8,
  },
  muted: { color: "var(--muted)" },

  // ── Two-pane shell ────────────────────────────────────────────────────────
  shell: {
    display: "flex",
    alignItems: "stretch",
    minHeight: "100dvh",
  },
  sidebar: {
    width: 340,
    flex: "none",
    borderRight: "1px solid var(--border)",
    display: "flex",
    flexDirection: "column",
    height: "100dvh",
    position: "sticky",
    top: 0,
  },
  // Content caps at the design's proportions (1100px frame − 340px sidebar)
  // instead of stretching across very wide windows.
  detail: {
    flex: 1,
    minWidth: 0,
    maxWidth: 828,
    padding: "30px 34px 34px",
  },

  // ── Sidebar: header + create form ─────────────────────────────────────────
  sideHead: {
    padding: "22px 20px 18px",
    borderBottom: "1px solid var(--border)",
  },
  sideTitleRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    margin: "0 0 14px",
  },
  sideTitle: { fontSize: "1.15rem", fontWeight: 600, margin: 0 },
  createForm: { display: "grid", gap: 10 },
  createInput: {
    width: "100%",
    padding: ".55rem .7rem",
    fontSize: ".9rem",
    color: "var(--fg)",
    background: "var(--field-bg)",
    border: "1px solid var(--border)",
    borderRadius: 8,
  },
  // Fields go quiet while the save is in flight.
  inputBusy: {
    background: "var(--field-readonly)",
    color: "var(--muted)",
  },
  slugRow: { display: "flex", alignItems: "stretch" },
  slugPrefix: {
    display: "flex",
    alignItems: "center",
    padding: "0 .55rem",
    fontSize: ".82rem",
    color: "var(--muted)",
    border: "1px solid var(--border)",
    borderRight: "none",
    borderRadius: "8px 0 0 8px",
    whiteSpace: "nowrap",
  },
  slugInput: {
    flex: 1,
    minWidth: 0,
    padding: ".5rem .7rem",
    fontSize: ".9rem",
    color: "var(--fg)",
    background: "var(--field-bg)",
    border: "1px solid var(--border)",
    borderRadius: "0 8px 8px 0",
  },
  fieldError: { borderColor: "var(--danger)" },
  slugErrorText: { fontSize: ".78rem", color: "var(--danger)" },
  // "edit that link" inside the slug-taken error.
  inlineLinkBtn: {
    padding: 0,
    font: "inherit",
    fontWeight: 600,
    color: "inherit",
    background: "transparent",
    border: "none",
    textDecoration: "underline",
    textUnderlineOffset: 2,
    cursor: "pointer",
  },
  saveBtn: {
    padding: ".55rem 1rem",
    fontSize: ".9rem",
    fontWeight: 600,
    color: "var(--accent-fg)",
    background: "var(--accent)",
    border: "none",
    borderRadius: 8,
    cursor: "pointer",
  },
  saveBtnBusy: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: ".5rem",
    background: "var(--accent-busy)",
    color: "#fff",
    cursor: "wait",
  },
  saveBtnDisabled: {
    color: "var(--muted)",
    background: "var(--surface)",
    cursor: "not-allowed",
  },
  formError: { fontSize: ".78rem", color: "var(--danger)" },
  // Green "Saved — carolanne.link/x7kq2" confirmation under the form.
  banner: {
    display: "flex",
    alignItems: "center",
    gap: ".6rem",
    padding: ".5rem .7rem",
    background: "var(--success-bg)",
    border: "1px solid var(--success-border)",
    borderRadius: 8,
  },
  bannerText: {
    flex: 1,
    minWidth: 0,
    fontSize: ".8rem",
    color: "var(--success)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  bannerSlug: {
    fontWeight: 600,
    fontFamily: "ui-monospace, Menlo, monospace",
  },
  bannerCopy: {
    padding: ".2rem .55rem",
    fontSize: ".72rem",
    fontWeight: 600,
    color: "var(--success)",
    background: "var(--field-bg)",
    border: "1px solid var(--success-border)",
    borderRadius: 6,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },

  // ── Sidebar: links list ───────────────────────────────────────────────────
  listHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "14px 20px 8px",
  },
  listLabel: {
    fontSize: ".7rem",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: ".07em",
    color: "var(--muted)",
  },
  sortSelect: {
    fontSize: ".75rem",
    color: "var(--muted)",
    background: "transparent",
    border: "none",
    padding: 0,
    cursor: "pointer",
  },
  list: {
    flex: 1,
    borderTop: "1px solid var(--border)",
    overflowY: "auto",
    minHeight: 0,
  },
  // Each row is a full-width button; the left border marks selection.
  row: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
    padding: "11px 20px",
    font: "inherit",
    textAlign: "left",
    color: "var(--fg)",
    background: "transparent",
    border: "none",
    borderBottom: "1px solid var(--border)",
    borderLeft: "3px solid transparent",
    cursor: "pointer",
  },
  rowSelected: {
    borderLeft: "3px solid var(--fg)",
    background: "var(--surface)",
  },
  // Rows are <button>s, so the inner layout lives on spans with explicit
  // display values.
  rowBody: { display: "block", flex: 1, minWidth: 0 },
  rowTop: { display: "flex", alignItems: "baseline", gap: 8 },
  rowSlug: { fontWeight: 600, fontSize: ".92rem" },
  rowClicks: { fontSize: ".75rem", color: "var(--muted)" },
  rowNote: {
    display: "block",
    fontSize: ".78rem",
    color: "var(--fg-soft)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  rowDest: {
    display: "block",
    fontSize: ".78rem",
    color: "var(--muted)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  rowChevron: { fontSize: ".9rem", color: "#9ca3af" },
  offBadge: {
    fontSize: ".7rem",
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: ".03em",
    color: "var(--danger)",
    border: "1px solid var(--danger)",
    borderRadius: 4,
    padding: "0 .3rem",
  },
  listEmpty: { padding: "16px 20px", fontSize: ".85rem", color: "var(--muted)" },
  // Quiet Touch ID setup affordance pinned under the list.
  sideFoot: {
    flex: "none",
    borderTop: "1px solid var(--border)",
    padding: "6px 12px",
  },
  sideFootNote: {
    padding: "0 .5rem .4rem",
    fontSize: ".72rem",
    color: "var(--muted)",
  },

  // ── Detail pane: header + actions ─────────────────────────────────────────
  detailHead: {
    display: "flex",
    alignItems: "flex-start",
    gap: 24,
    margin: "0 0 24px",
  },
  detailHeadLeft: { flex: 1, minWidth: 0 },
  detailTitle: {
    fontSize: "1.5rem",
    fontWeight: 600,
    margin: "0 0 4px",
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    minWidth: 0,
  },
  detailTitleText: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  detailSub: {
    fontSize: ".85rem",
    color: "var(--muted)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  actionRow: {
    display: "flex",
    alignItems: "center",
    gap: ".4rem",
    flexWrap: "wrap",
    marginTop: 14,
  },
  // Transparent border keeps the height identical to the bordered variants.
  btnPrimary: {
    padding: ".45rem .8rem",
    fontSize: ".85rem",
    fontWeight: 600,
    color: "var(--accent-fg)",
    background: "var(--accent)",
    border: "1px solid transparent",
    borderRadius: 8,
    cursor: "pointer",
  },
  btnCopied: {
    color: "var(--success)",
    background: "var(--success-bg)",
    border: "1px solid var(--success-border)",
  },
  btnSecondary: {
    padding: ".45rem .8rem",
    fontSize: ".85rem",
    fontWeight: 600,
    color: "var(--fg)",
    background: "var(--field-bg)",
    border: "1px solid var(--border)",
    borderRadius: 8,
    cursor: "pointer",
  },
  btnDangerText: {
    padding: ".45rem .8rem",
    fontSize: ".85rem",
    fontWeight: 600,
    color: "var(--danger)",
    background: "var(--field-bg)",
    border: "1px solid var(--border)",
    borderRadius: 8,
    cursor: "pointer",
  },
  btnDangerSolid: {
    padding: ".45rem .8rem",
    fontSize: ".85rem",
    fontWeight: 600,
    color: "#fff",
    background: "var(--danger)",
    border: "1px solid transparent",
    borderRadius: 8,
    cursor: "pointer",
  },
  confirmText: { fontSize: ".85rem", color: "var(--fg)" },
  confirmSlug: { fontWeight: 600, fontFamily: "ui-monospace, Menlo, monospace" },
  // Inline destination editor that replaces the "→ destination" line.
  editInput: {
    width: "100%",
    padding: ".5rem .7rem",
    fontSize: ".9rem",
    color: "var(--fg)",
    background: "var(--field-bg)",
    border: "1px solid var(--border)",
    borderRadius: 8,
  },

  // ── Detail pane: QR panel ─────────────────────────────────────────────────
  qrPanel: {
    flex: "none",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 8,
  },
  qrBox: {
    background: "#fff",
    border: "1px solid var(--border)",
    borderRadius: 6,
    overflow: "hidden",
    lineHeight: 0,
  },
  // Parks the print-resolution canvas offscreen but rendered, so copy /
  // download can read it.
  qrHidden: {
    position: "absolute",
    width: 0,
    height: 0,
    overflow: "hidden",
  },
  qrCopyBtn: {
    width: "100%",
    padding: ".45rem .8rem",
    fontSize: ".8rem",
    fontWeight: 600,
    color: "var(--fg)",
    background: "var(--field-bg)",
    border: "1px solid var(--border)",
    borderRadius: 8,
    cursor: "pointer",
  },
  qrCopyBtnCopied: {
    color: "var(--success)",
    background: "var(--success-bg)",
    border: "1px solid var(--success-border)",
  },
  qrDownloadBtn: {
    padding: 0,
    fontSize: ".75rem",
    fontWeight: 600,
    color: "var(--muted)",
    background: "transparent",
    border: "none",
    textDecoration: "underline",
    textUnderlineOffset: 2,
    cursor: "pointer",
  },

  // ── Detail pane: note ─────────────────────────────────────────────────────
  section: { margin: "0 0 22px" },
  sectionLabel: {
    fontSize: ".7rem",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: ".07em",
    color: "var(--muted)",
    marginBottom: 8,
  },
  noteBox: {
    padding: ".65rem .75rem",
    fontSize: ".9rem",
    color: "var(--fg)",
    background: "var(--field-bg)",
    border: "1px solid var(--border)",
    borderRadius: 8,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  // With no note yet, the whole box is the click target and reads like an
  // empty field with placeholder text.
  noteAddBox: {
    display: "block",
    width: "100%",
    padding: ".65rem .75rem",
    fontSize: ".9rem",
    fontFamily: "inherit",
    textAlign: "left",
    color: "var(--muted)",
    background: "var(--field-bg)",
    border: "1px solid var(--border)",
    borderRadius: 8,
    cursor: "pointer",
  },
  noteEditBtn: {
    marginLeft: ".5rem",
    padding: 0,
    fontSize: "1rem",
    fontWeight: 600,
    color: "var(--muted)",
    background: "transparent",
    border: "none",
    textDecoration: "underline",
    textUnderlineOffset: 2,
    whiteSpace: "nowrap",
    cursor: "pointer",
  },
  noteTextarea: {
    width: "100%",
    padding: ".65rem .75rem",
    fontSize: ".9rem",
    fontFamily: "inherit",
    color: "var(--fg)",
    background: "var(--field-bg)",
    border: "1px solid var(--border)",
    borderRadius: 8,
    resize: "vertical",
  },
  noteActions: { display: "flex", gap: ".4rem", marginTop: 8 },

  // ── Stats card (dashboard) + shared chart / visit rows ────────────────────
  statsCard: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: "16px 18px 14px",
    margin: "0 0 24px",
  },
  statsHeadRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "1rem",
    marginBottom: 10,
  },
  segmented: {
    display: "flex",
    border: "1px solid var(--border)",
    borderRadius: 7,
    overflow: "hidden",
  },
  segBtn: {
    padding: ".25rem .65rem",
    fontSize: ".72rem",
    fontWeight: 600,
    color: "var(--muted)",
    background: "var(--field-bg)",
    border: "none",
    cursor: "pointer",
  },
  segBtnActive: {
    color: "var(--accent-fg)",
    background: "var(--accent)",
  },
  statsSummary: {
    display: "flex",
    gap: "1.25rem",
    flexWrap: "wrap",
    marginBottom: 12,
    fontSize: ".75rem",
    color: "var(--muted)",
  },
  statStrong: { fontWeight: 600, color: "var(--fg)" },
  chart: {
    display: "flex",
    alignItems: "flex-end",
    gap: 3,
    height: 80,
  },
  bar: {
    flex: 1,
    minWidth: 0,
    background: "var(--border)",
    borderRadius: "2px 2px 0 0",
  },
  barPeak: { background: "var(--accent)" },
  axis: {
    display: "flex",
    justifyContent: "space-between",
    marginTop: 6,
    fontSize: ".7rem",
    color: "var(--muted)",
  },
  statsMsg: { fontSize: ".8rem", color: "var(--muted)" },
  visitsSection: {
    marginTop: 16,
    paddingTop: 14,
    borderTop: "1px solid var(--border)",
  },
  visitsHeadRow: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: "1rem",
    marginBottom: 6,
  },
  visitsTitle: { fontSize: ".75rem", fontWeight: 600, color: "var(--fg)" },
  visitsBreakdown: {
    display: "flex",
    gap: ".9rem",
    fontSize: ".75rem",
    color: "var(--muted)",
    whiteSpace: "nowrap",
  },
  visitRow: {
    display: "flex",
    alignItems: "baseline",
    gap: 12,
    padding: ".45rem 0",
    borderTop: "1px solid var(--border)",
  },
  vWhen: {
    fontSize: ".75rem",
    color: "var(--muted)",
    whiteSpace: "nowrap",
    width: 96,
  },
  vWhere: {
    fontWeight: 600,
    fontSize: ".85rem",
    whiteSpace: "nowrap",
    width: 110,
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  vDevice: {
    flex: 1,
    minWidth: 0,
    fontSize: ".8rem",
    color: "var(--muted)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  vSource: {
    fontWeight: 600,
    fontSize: ".85rem",
    whiteSpace: "nowrap",
    textAlign: "right",
  },
  vSourceDenied: { color: "var(--danger)" },
  visitsFoot: {
    display: "flex",
    alignItems: "baseline",
    gap: ".6rem",
    paddingTop: ".5rem",
    fontSize: ".75rem",
    color: "var(--muted)",
  },
  viewAllLink: { fontWeight: 600, color: "var(--fg)" },

  // ── Full visit-history page (/admin/:slug/visits) ─────────────────────────
  visPage: {
    maxWidth: 1100,
    margin: "0 auto",
    padding: "26px 34px 34px",
  },
  visBack: {
    display: "inline-block",
    fontSize: ".8rem",
    color: "var(--muted)",
    textDecoration: "none",
    marginBottom: 14,
  },
  visHeadRow: {
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: "1rem",
    flexWrap: "wrap",
    marginBottom: 18,
  },
  visTitle: { fontSize: "1.5rem", fontWeight: 600, margin: "0 0 4px" },
  visCounts: {
    display: "flex",
    gap: "1.25rem",
    fontSize: ".8rem",
    color: "var(--muted)",
  },
  visChart: { margin: "0 0 20px" },
  visTableHead: {
    display: "flex",
    alignItems: "baseline",
    gap: 12,
    padding: ".35rem 0",
    fontSize: ".7rem",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: ".07em",
    color: "var(--muted)",
  },
  // The full-page table gets roomier When / Where columns than the dashboard.
  colWhenWide: { width: 130 },
  colWhereWide: { width: 140 },
  thDevice: { flex: 1, minWidth: 0 },
  pager: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: ".7rem",
    borderTop: "1px solid var(--border)",
    fontSize: ".75rem",
    color: "var(--muted)",
  },
  pagerBtns: { display: "flex", gap: ".4rem" },
  pageBtn: {
    padding: ".2rem .55rem",
    fontSize: ".72rem",
    fontWeight: 600,
    color: "var(--fg)",
    background: "var(--field-bg)",
    border: "1px solid var(--border)",
    borderRadius: 6,
    cursor: "pointer",
  },
  pageBtnDisabled: { color: "#9ca3af", cursor: "not-allowed" },
  visMsg: { fontSize: ".9rem", color: "var(--muted)" },
};
